# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/65767/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12332-DESKTOP-BKSDDJC/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.cache/wt [current_project]
set_property parent.project_path D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/new/LED_Display.v
  D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/new/blueteeth_decoder.v
  D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/new/clock_1hz.v
  D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/new/clock_50khz.v
  D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/new/clock_9600khz.v
  D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/new/read_accr_sensor.v
  D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/new/read_blueteeth.v
  D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/new/snake_control.v
  D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/new/LED_test.v
}
read_ip -quiet D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/constrs_1/imports/lab_11/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/¿œ”≤≈Ã/digital/lab_11/lab_11_test/lab_11_test.srcs/constrs_1/imports/lab_11/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top LED_test -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LED_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LED_test_utilization_synth.rpt -pb LED_test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
