# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/nexys4.xdc

# IP: ip/c_counter_binary_0/c_counter_binary_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_0 || ORIG_REF_NAME==c_counter_binary_0} -quiet] -quiet
