# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/gyx verilog/digital/lab_9/lab9_3_1/lab9_3_1.srcs/sources_1/ip/counter_f2/counter_f2.xci
# IP: The module: 'counter_f2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/gyx verilog/digital/lab_9/lab9_3_1/lab9_3_1.srcs/sources_1/ip/counter_f2/counter_f2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_f2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: h:/gyx verilog/digital/lab_9/lab9_3_1/lab9_3_1.srcs/sources_1/ip/counter_f2/counter_f2.xci
# IP: The module: 'counter_f2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/gyx verilog/digital/lab_9/lab9_3_1/lab9_3_1.srcs/sources_1/ip/counter_f2/counter_f2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_f2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
